from Blueprints.auth.authentication import auth_bp
from Blueprints.converter_routes import (
    aac_mp3_bp,
    avi_mp4_bp,
    csv_xlsx_bp,
    doc_docx_bp,
    doc_pdf_bp,
    docx_pdf_bp,
    docx_txt_bp,
    docx_xlsx_bp,
    files_zip_bp,
    flac_mp3_bp,
    flac_wav_bp,
    heic_jpg_bp,
    heic_png_bp,
    html_docx_bp,
    html_pdf_bp,
    images_pdf_bp,
    jpg_pdf_bp,
    jpg_png_bp,
    jpg_svg_bp,
    jpg_webp_bp,
    json_csv_bp,
    json_xlsx_bp,
    md_docx_bp,
    md_pdf_bp,
    mkv_mp4_bp,
    mov_mp4_bp,
    mp3_mp4_bp,
    mp3_wav_bp,
    mp4_gif_bp,
    mp4_mkv_bp,
    mp4_mov_bp,
    mp4_mp3_bp,
    mp4_wav_bp,
    mp4_webm_bp,
    odp_pdf_bp,
    odp_pptx_bp,
    ods_pdf_bp,
    ods_xlsx_bp,
    odt_docx_bp,
    odt_pdf_bp,
    ogg_mp3_bp,
    ogg_wav_bp,
    pdf_compress_bp,
    pdf_csv_bp,
    pdf_docx_bp,
    pdf_edit_bp,
    pdf_extract_images_bp,
    pdf_html_bp,
    pdf_jpg_bp,
    pdf_merge_bp,
    pdf_png_bp,
    pdf_pptx_bp,
    pdf_protect_bp,
    pdf_rotate_bp,
    pdf_split_bp,
    pdf_txt_bp,
    pdf_unlock_bp,
    pdf_xlsx_bp,
    png_jpg_bp,
    png_svg_bp,
    png_webp_bp,
    ppt_pdf_bp,
    ppt_pptx_bp,
    pptx_pdf_bp,
    svg_jpg_bp,
    svg_png_bp,
    txt_docx_bp,
    txt_pdf_bp,
    wav_flac_bp,
    wav_mp3_bp,
    webm_mp4_bp,
    webp_jpg_bp,
    webp_png_bp,
    wma_mp3_bp,
    xls_pdf_bp,
    xls_xlsx_bp,
    xlsx_csv_bp,
    xlsx_docx_bp,
    xlsx_json_bp,
    xlsx_pdf_bp,
)
from Blueprints.main.checkout_routes import payments_bp
from Blueprints.main.home import home_bp
from Blueprints.main.planos import planos_bp
from Blueprints.main.webhook_routes import webhook_bp

MAIN_BLUEPRINTS = (
    auth_bp,
    home_bp,
    planos_bp,
    webhook_bp,
    payments_bp,
)

DOCUMENT_BLUEPRINTS = (
    csv_xlsx_bp,
    doc_docx_bp,
    doc_pdf_bp,
    docx_pdf_bp,
    docx_txt_bp,
    docx_xlsx_bp,
    html_docx_bp,
    html_pdf_bp,
    files_zip_bp,
    jpg_pdf_bp,
    json_csv_bp,
    json_xlsx_bp,
    md_docx_bp,
    md_pdf_bp,
    odp_pdf_bp,
    odp_pptx_bp,
    ods_pdf_bp,
    ods_xlsx_bp,
    odt_docx_bp,
    odt_pdf_bp,
    pdf_extract_images_bp,
    pdf_csv_bp,
    pdf_docx_bp,
    pdf_html_bp,
    pdf_jpg_bp,
    pdf_png_bp,
    pdf_pptx_bp,
    pdf_txt_bp,
    pdf_xlsx_bp,
    pdf_merge_bp,
    pdf_split_bp,
    pdf_compress_bp,
    pdf_edit_bp,
    pdf_protect_bp,
    pdf_rotate_bp,
    pdf_unlock_bp,
    ppt_pdf_bp,
    ppt_pptx_bp,
    pptx_pdf_bp,
    txt_docx_bp,
    txt_pdf_bp,
    xls_pdf_bp,
    xls_xlsx_bp,
    xlsx_csv_bp,
    xlsx_docx_bp,
    xlsx_json_bp,
    xlsx_pdf_bp,
)

IMAGE_BLUEPRINTS = (
    heic_jpg_bp,
    heic_png_bp,
    images_pdf_bp,
    jpg_png_bp,
    jpg_svg_bp,
    jpg_webp_bp,
    png_jpg_bp,
    png_svg_bp,
    png_webp_bp,
    svg_jpg_bp,
    svg_png_bp,
    webp_jpg_bp,
    webp_png_bp,
)

VIDEO_BLUEPRINTS = (
    avi_mp4_bp,
    mkv_mp4_bp,
    mov_mp4_bp,
    mp4_gif_bp,
    mp4_mkv_bp,
    mp4_mov_bp,
    mp4_mp3_bp,
    mp4_wav_bp,
    mp4_webm_bp,
    webm_mp4_bp,
)

AUDIO_BLUEPRINTS = (
    aac_mp3_bp,
    flac_mp3_bp,
    flac_wav_bp,
    mp3_mp4_bp,
    mp3_wav_bp,
    ogg_mp3_bp,
    ogg_wav_bp,
    wav_flac_bp,
    wav_mp3_bp,
    wma_mp3_bp,
)

ALL_BLUEPRINTS = (
    *MAIN_BLUEPRINTS,
    *DOCUMENT_BLUEPRINTS,
    *IMAGE_BLUEPRINTS,
    *VIDEO_BLUEPRINTS,
    *AUDIO_BLUEPRINTS,
)


def register_blueprints(app):
    for blueprint in ALL_BLUEPRINTS:
        app.register_blueprint(blueprint)
