"""mensagem

Revision ID: 27b1482e9ad0
Revises: 
Create Date: 2026-04-18 15:44:47.274382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b1482e9ad0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plano', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('usos', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['senha'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('usos')
        batch_op.drop_column('plano')

    # ### end Alembic commands ###
